### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by SANTHOSH17-DOT** [SANTHOSH17-DOT/HODL#17]
- Include directory structure
- Make it prettier. Include banners(screenshots) at the start of the file
- A section for contributors
- Mention the contract address and the network it's deployed on
- Add env setup instructions for both frontend and the contract directory

**Comment by SANTHOSH17-DOT** [comment]
@Anuragwagh You may go ahead

**Comment by nerdy-nakul** [comment]
is this issue still open, may i contribute ?

**Comment by SANTHOSH17-DOT** [comment]
@nerdy-nakul It's open. You may work on this.

**Comment by Code1705** [comment]
I want to work on this issue to make a proper readme file with beautiful emojis and proper info about the contribution process to look more atttractive , please assign me under JWOC.

**Comment by SANTHOSH17-DOT** [comment]
@Code1705 Thank you for showing your interest. But, this issue has been assigned and will be closed soon
