### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by AnishDubey27** [SANTHOSH17-DOT/HODL#19]
Problem Statement:
There are many first time contributors who might be unable to use the terminal efficiently.

Solution:
We can make some changes in the CONTRIBUTING.md file and add a step by step process how a person can contribute to the project with the help of GITHUB DESKTOP application, without the need to write a single command manually.
I would like to work on the same issue.

**Comment by SANTHOSH17-DOT** [comment]
You may go ahead

**Comment by AnishDubey27** [comment]
Please add SWOC labels as well.

**Comment by SANTHOSH17-DOT** [comment]
I'm giving SWOC - Beginner to this PR.
