### ISSUE TITLE
🧑‍💻 Add Contributors and Admin Details 

### ISSUE THREAD

**Issue by Suryansh1720001** [SANTHOSH17-DOT/HODL#31]
Hello @SANTHOSH17-DOT 

**Is your feature request related to a problem? Please describe.**
### Features that I want to add in README FILE

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive

**Describe the solution you'd like**

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by SANTHOSH17-DOT** [comment]
Thank you for showing your interest. But the readme looks fine

**Comment by Suryansh1720001** [comment]
@SANTHOSH17-DOT Okay fine 👍
